### ISSUE TITLE
Write script to create explicit feature matrix E

### ISSUE THREAD

**Issue by santacruz91** [CSE547-kollerz-s9wischu/CSE547-ColdStart#3]

**Comment by santacruz91** [comment]
For now, we use as explicit features
* (Binned) Year
* bool[] Genre

**Comment by s9wischu** [comment]
I generated the histogram for the 100k data set (there was one connection loss, so there is one sample missing)
For the years I would suggest using 10 year interval bins until 1989 and after that
each year in its own bin, since the numbers increases a lot.
For the genres we can use the binary vector.
I will generate the data for the 20m data set to check the histograms for that

**Comment by s9wischu** [comment]
I generated the histogram for the 20m data set.
To create the bins I will create year categories in a kind of logarithmic behavior.
Bin categories for the years
< 1930	(~40 years)
< 1955
< 1975
< 1985
< 1990
rest of the years (<= 1990) each in one bin

For genres we use bool[] Genre

**Comment by s9wischu** [comment]
To decrease the number of features to handle we use just one element in the feature vector to express the year category as follows:

Because of the increasing number of movies over the years we categorize the year in a kind of logarithmic way.
Bin categories for the years
< 1930: 0
< 1955: 1
< 1975: 2
< 1985: 3
< 1990: 4
for the rest of the years (>= 1990), each one has its own category: category = year - 1990 + 5

explicit feature matrix createt (ml-20m-extra/explicit_featurs.csv)

**Comment by s9wischu** [comment]
to avoid multiplication issues we changed the categories to start with 1 instead of 0.
